name: tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.10"
          - "3.11"
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Cache python packages
      uses: actions/cache@v3
      env:
        cache-name: test-python-packages
      with:
        path: '~/.local/**/site-packages'
        key: ${{ runner.os }}-${{ matrix.python }}-${{ env.cache-name }}-${{ hashFiles('requirements/**/*.txt') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.python }}-${{ env.cache-name }}-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/base.txt --user
        pip install -r requirements/lint.txt --user

    - name: Check with black
      run: |
        python -m black --check pytest_runtime_types
        python -m black --check tests

    - name: Check with isort
      run: |
        python -m isort --profile black --check-only pytest_runtime_types
        python -m isort --profile black --check-only tests

    # - name: Check with pylint
    #   run: |
    #     ./lint_all.sh

    - name: Test with pytest
      env:
        PYTHONPATH: ".:./tests/integration_tests"
        PYTEST_PLUGINS: pytest_runtime_types
      run: |
        pip install -e .
        python -m pytest --source ./tests/integration_tests/tested_code tests
